---
abstract: 'skips tests unless executable exists'
author:
  - 'dann <techmemo@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Skip-UnlessExistsExecutable
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  File::Which: 1.09
  Filter::Util::Call: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/dann/p5-test-skip-unlessexistsexecutable.git
version: 0.04
